---
outlines:
    default: { width: 50, height: 50 }
    menu: { width: 50, height: 50 }
    altline: { width: 50, height: 30 }
    spaceline: { width: 150, height: 30 }
    special: { width: 50, height: 50 }
    action: { width: 50, height: 50 }
    fkey: { width: 50, height: 50 }

views:
    base:
        - "Shift_A Shift_N Shift_I preferences "
        - "Shift_U Shift_O Shift_R 1"
        - "Shift_T Shift_E Shift_S BackSpace"
        - " space Return "
    aKey:
        - "a . . preferences "
        - ". v . Shift_A"
        - ". . . BackSpace"
        - " space Return "
    nKey:
        - ". n . preferences "
        - ". l . Shift_N"
        - ". . . BackSpace"
        - " space Return "
    iKey:
        - ". . i preferences "
        - ". x . Shift_I"
        - ". . . BackSpace"
        - " space Return "
    uKey:
        - ". . . preferences "
        - "u k . Shift_U"
        - ". . . BackSpace"
        - " space Return "
    oKey:
        - "q h p preferences "
        - "c o b Shift_O"
        - "g d j BackSpace"
        - " space Return "
    rKey:
        - ". . . preferences "
        - ". m r Shift_R"
        - ". . . BackSpace"
        - " space Return "
    tKey:
        - ". . . preferences "
        - ". y . Shift_T"
        - "t . . BackSpace"
        - " space Return "
    eKey:
        - ". . . preferences "
        - ". w . Shift_E"
        - ". e . BackSpace"
        - " space Return "
    sKey:
        - ". . . preferences "
        - ". f . Shift_S"
        - ". . s BackSpace"
        - " space Return "

buttons:
    Shift_A:
        action:
            locking:
                lock_view: "aKey"
                unlock_view: "base"
        outline: "special"
        label: "a\n\tv"
    Shift_N:
        action:
            locking:
                lock_view: "nKey"
                unlock_view: "base"
        outline: "special"
        label: "n"
    Shift_I:
        action:
            locking:
                lock_view: "iKey"
                unlock_view: "base"
        outline: "special"
        label: "i"
    Shift_U:
        action:
            locking:
                lock_view: "uKey"
                unlock_view: "base"
        outline: "special"
        label: "u"
    Shift_O:
        action:
            locking:
                lock_view: "oKey"
                unlock_view: "base"
        outline: "special"
        label: "qhp\ncob\ngdj"
    Shift_R:
        action:
            locking:
                lock_view: "rKey"
                unlock_view: "base"
        outline: "special"
        label: "r"
    Shift_T:
        action:
            locking:
                lock_view: "tKey"
                unlock_view: "base"
        outline: "special"
        label: "t"
    Shift_E:
        action:
            locking:
                lock_view: "eKey"
                unlock_view: "base"
        outline: "special"
        label: "e"
    Shift_S:
        action:
            locking:
                lock_view: "sKey"
                unlock_view: "base"
        outline: "special"
        label: "s"
    Shift_L:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "special"
        icon: "key-shift"
    Ctrl:
        modifier: "Control"
        outline: "action"
        label: "Ctrl"
    Alt:
        modifier: "Alt"
        outline: "action"
        label: "Alt"
    BackSpace:
        outline: "special"
        icon: "edit-clear-symbolic"
        action: "erase"
    Menu:
        outline: "menu"
        keysym: "Menu"
    preferences:
        action: "show_prefs"
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_letters:
        action:
            set_view: "base"
        outline: "altline"
        label: "abc"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "altline"
        label: "[{/"
    show_eschars:
        action:
            locking:
                lock_view: "eschars"
                unlock_view: "base"
        outline: "altline"
        label: "func"
    space:
        outline: "spaceline"
        label: " "
        text: " "
    Return:
        outline: "altline"
        icon: "key-enter"
        keysym: "Return"
    F1:
        outline: "fkey"
        keysym: "F1"
    F2:
        outline: "fkey"
        keysym: "F2"
    F3:
        outline: "fkey"
        keysym: "F3"
    F4:
        outline: "fkey"
        keysym: "F4"
    F5:
        outline: "fkey"
        keysym: "F5"
    F6:
        outline: "fkey"
        keysym: "F6"
    F7:
        outline: "fkey"
        keysym: "F7"
    F8:
        outline: "fkey"
        keysym: "F8"
    F9:
        outline: "fkey"
        keysym: "F9"
    F10:
        outline: "fkey"
        keysym: "F10"
    F11:
        outline: "fkey"
        keysym: "F11"
    F12:
        outline: "fkey"
        keysym: "F12"
    Esc:
        outline: "action"
        keysym: "Escape"
    Home:
        outline: "action"
        keysym: "Home"
    End:
        outline: "action"
        keysym: "End"
    Del:
        outline: "altline"
        keysym: "Delete"
    PgUp:
        outline: "action"
        keysym: "Page_Up"
    PgDn:
        outline: "action"
        keysym: "Page_Down"
    Tab:
        outline: "action"
        keysym: "Tab"
    "↑":
        outline: "action"
        keysym: "Up"
    "↓":
        outline: "action"
        keysym: "Down"
    "←":
        outline: "action"
        keysym: "Left"
    "→":
        outline: "action"
        keysym: "Right"
