---
outlines:
    default: { width: 50, height: 50 }
    menu: { width: 100, height: 50 }
    altline: { width: 50, height: 50 }
    spaceline: { width: 150, height: 50 }
    special: { width: 50, height: 50 }
    action: { width: 50, height: 50 }
    fkey: { width: 50, height: 50 }

views:
    base:
        - "a n i preferences "
        - "u o r 1"
        - "t e s BackSpace"
        - " space Return "

    upper:
        - "[ { } ("
        - "G C R L"
        - "A O E U"
        - "Q J K preferences "

buttons:
    Shift_L:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "altline"
        icon: "key-shift"
    Ctrl:
        modifier: "Control"
        outline: "action"
        label: "Ctrl"
    Alt:
        modifier: "Alt"
        outline: "action"
        label: "Alt"
    BackSpace:
        outline: "altline"
        icon: "edit-clear-symbolic"
        action: "erase"
    Menu:
        outline: "menu"
        keysym: "Menu"
    preferences:
        action: "show_prefs"
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_letters:
        action:
            set_view: "base"
        outline: "altline"
        label: "abc"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "altline"
        label: "[{/"
    show_eschars:
        action:
            locking:
                lock_view: "eschars"
                unlock_view: "base"
        outline: "altline"
        label: "func"
    space:
        outline: "spaceline"
        label: " "
        text: " "
    Return:
        outline: "altline"
        icon: "key-enter"
        keysym: "Return"
    F1:
        outline: "fkey"
        keysym: "F1"
    F2:
        outline: "fkey"
        keysym: "F2"
    F3:
        outline: "fkey"
        keysym: "F3"
    F4:
        outline: "fkey"
        keysym: "F4"
    F5:
        outline: "fkey"
        keysym: "F5"
    F6:
        outline: "fkey"
        keysym: "F6"
    F7:
        outline: "fkey"
        keysym: "F7"
    F8:
        outline: "fkey"
        keysym: "F8"
    F9:
        outline: "fkey"
        keysym: "F9"
    F10:
        outline: "fkey"
        keysym: "F10"
    F11:
        outline: "fkey"
        keysym: "F11"
    F12:
        outline: "fkey"
        keysym: "F12"
    Esc:
        outline: "action"
        keysym: "Escape"
    Home:
        outline: "action"
        keysym: "Home"
    End:
        outline: "action"
        keysym: "End"
    Del:
        outline: "altline"
        keysym: "Delete"
    PgUp:
        outline: "action"
        keysym: "Page_Up"
    PgDn:
        outline: "action"
        keysym: "Page_Down"
    Tab:
        outline: "action"
        keysym: "Tab"
    "↑":
        outline: "action"
        keysym: "Up"
    "↓":
        outline: "action"
        keysym: "Down"
    "←":
        outline: "action"
        keysym: "Left"
    "→":
        outline: "action"
        keysym: "Right"
